---
# Copyright 2018 widdix GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
AWSTemplateFormatVersion: '2010-09-09'
Description: 'cfn-modules: Amazon CloudFront distribution'
# cfn-modules:implements(ExposeArn, ExposeName, LambdaDependency)
Parameters:
  OriginBucketModule:
    Description: 'Required stack name of s3-bucket module used to store static content.'
    Type: String
  LogsBucketModule:
    Description: 'Optional but recommended stack name of s3-bucket module to store access logs.'
    Type: String
    Default: ''
Conditions:
  HasLogsBucketModule: !Not [!Equals [!Ref LogsBucketModule, '']]
Resources:
  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          - OPTIONS
          CachedMethods:
          - GET
          - HEAD
          - OPTIONS
          Compress: true
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          DefaultTTL: 3600 # in seconds
          MaxTTL: 86400 # in seconds
          MinTTL: 60 # in seconds
          TargetOriginId: s3origin
          ViewerProtocolPolicy: 'redirect-to-https'
        Enabled: true
        HttpVersion: http2and3
        IPV6Enabled: true
        Logging: !If [HasLogsBucketModule, {Bucket: {'Fn::ImportValue': !Sub '${LogsBucketModule}-DomainName'}, Prefix: !Ref 'AWS::StackName'}, !Ref 'AWS::NoValue']
        Origins:
        - DomainName: {'Fn::ImportValue': !Sub '${OriginBucketModule}-RegionalDomainName'}
          Id: s3origin
          S3OriginConfig:
            OriginAccessIdentity: {'Fn::ImportValue': !Sub '${OriginBucketModule}-CloudFrontOriginAccessIdentity'}
        PriceClass: 'PriceClass_All'
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
          MinimumProtocolVersion: 'TLSv1.2_2021'
Outputs:
  ModuleId:
    Value: 'cloudfront'
  ModuleVersion:
    Value: '1.0.0'
  StackName:
    Value: !Ref 'AWS::StackName'
  DistributionDomainName:
    Value: !GetAtt 'CloudFrontDistribution.DomainName'
    Export:
      Name: !Sub '${AWS::StackName}-DistributionDomainName'
  DistributionId:
    Value: !GetAtt 'CloudFrontDistribution.Id'
    Export:
      Name: !Sub '${AWS::StackName}-DistributionId'
